
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aws-study

# 권한을 정의합니다.
permissions:
  - object: /home/ubuntu/aws-study/
    owner: ubuntu
    group: ubuntu

# 배포단계에서 진행하는 훅 스크립트를 정의합니다.
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu